import { NextResponse } from 'next/server';
import jsPDF from 'jspdf';

type DocumentType = 'creative-brief' | 'ad-script' | 'iteration-report';

const DOCUMENT_COPY: Record<DocumentType, {
  buildTitle: (company: string) => string;
  subtitle: string;
  defaultFileName: string;
}> = {
  'creative-brief': {
    buildTitle: (company) => `Creative Brief for ${company}`,
    subtitle: 'Generated with APSICS Creative Intelligence',
    defaultFileName: 'creative-brief',
  },
  'ad-script': {
    buildTitle: (company) => `Ad Script for ${company}`,
    subtitle: 'Generated with APSICS Media AI Ad Script Generator',
    defaultFileName: 'ad-script',
  },
  'iteration-report': {
    buildTitle: (company) => `Creative Intelligence Report for ${company}`,
    subtitle: 'Generated with APSICS Media Ad Iteration Toolkit',
    defaultFileName: 'creative-intelligence-report',
  },
};

export async function POST(request: Request) {
  try {
    const { content, companyName, documentType }: {
      content?: string;
      companyName?: string;
      documentType?: DocumentType;
    } = await request.json();

    if (!content || typeof content !== 'string') {
      return NextResponse.json({ error: 'Document content is required' }, { status: 400 });
    }

    const normalizedType: DocumentType = documentType && documentType in DOCUMENT_COPY ? documentType : 'creative-brief';
    const copy = DOCUMENT_COPY[normalizedType];

    const displayCompany = companyName?.trim() || 'Your Campaign';

    const doc = new jsPDF();

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(20);
    doc.setTextColor(17, 24, 39);
    doc.text(copy.buildTitle(displayCompany), 20, 30);

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(12);
    doc.setTextColor(75, 85, 99);
    doc.text(copy.subtitle, 20, 45);

    doc.setDrawColor(229, 231, 235);
    doc.line(20, 55, 190, 55);

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(17, 24, 39);
    const splitContent = doc.splitTextToSize(content, 170);
    doc.text(splitContent, 20, 70);

    const pageHeight = doc.internal.pageSize.height;
    doc.setFontSize(8);
    doc.setTextColor(107, 114, 128);
    doc.text('Generated by APSICS Media Creative Intelligence Toolkit', 20, pageHeight - 20);
    doc.text(new Date().toLocaleDateString(), 170, pageHeight - 20);

    const pdfBuffer = Buffer.from(doc.output('arraybuffer'));

    const safeCompany = displayCompany.toLowerCase().replace(/\s+/g, '-');
    const filename = `${copy.defaultFileName}-${safeCompany}.pdf`;

    return new Response(pdfBuffer, {
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="${filename}"`,
      },
    });
  } catch (error) {
    console.error('PDF generation error:', error);
    return NextResponse.json(
      { error: 'Failed to generate PDF' },
      { status: 500 }
    );
  }
}
