import { NextResponse } from 'next/server';
import jsPDF from 'jspdf';

export async function POST(request: Request) {
  try {
    const { content, companyName } = await request.json();

    if (!content || typeof content !== 'string') {
      return NextResponse.json({ error: 'Creative brief content is required' }, { status: 400 });
    }

    const displayCompany = companyName?.trim() || 'Your Company';

    // Create new PDF document
    const doc = new jsPDF();

    // Set fonts and colors
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(20);
    doc.setTextColor(17, 24, 39); // gray-900

    // Add title
    doc.text(`Creative Brief for ${displayCompany}`, 20, 30);

    // Add subtitle
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(12);
    doc.setTextColor(75, 85, 99); // gray-600
    doc.text('Generated with APSICS Creative Intelligence', 20, 45);

    // Add horizontal line
    doc.setDrawColor(229, 231, 235); // gray-200
    doc.line(20, 55, 190, 55);

    // Add content
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(17, 24, 39); // gray-900

    // Split content into lines that fit the page width
    const splitContent = doc.splitTextToSize(content, 170);
    doc.text(splitContent, 20, 70);

    // Add footer
    const pageHeight = doc.internal.pageSize.height;
    doc.setFontSize(8);
    doc.setTextColor(107, 114, 128); // gray-500
    doc.text('Generated by APSICS Media Creative Intelligence Toolkit', 20, pageHeight - 20);
    doc.text(new Date().toLocaleDateString(), 170, pageHeight - 20);

    // Convert to buffer
    const pdfBuffer = Buffer.from(doc.output('arraybuffer'));

    return new Response(pdfBuffer, {
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="creative-brief-${displayCompany.toLowerCase().replace(/\s+/g, '-')}.pdf"`,
      },
    });
  } catch (error) {
    console.error('PDF generation error:', error);
    return NextResponse.json(
      { error: 'Failed to generate PDF' },
      { status: 500 }
    );
  }
}